source :rubygems
gem 'compass'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongo'
gem 'bson_ext'
gem 'mongoid'
gem 'warden'
gem 'haml'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'rack-flash'
gem 'mail'
gem 'thin'